apiVersion: v1
kind: Service
metadata:
  name: jmeter-workers-svc
  labels:
    app: java-app-metrics-9097
    jmeter_mode: worker
spec:
  clusterIP: None
  selector:
    jmeter_mode: worker
  ports:
    - name: first
      protocol: TCP
      port: 1099
      targetPort: 1099
    - name: second
      protocol: TCP
      port: 50000
      targetPort: 50000
    - name: jvm-metrics
      protocol: TCP
      port: 9097
      targetPort: 9097

