apiVersion: v1
kind: Service
metadata:
  name: jmeter-controller-svc
  labels:
    app: java-app-metrics-9097
    jmeter_mode: controller
spec:
  clusterIP: None
  selector:
    jmeter_mode: controller
  ports:
    - name: jvm-metrics
      port: 9097
      targetPort: 9097
      protocol: TCP

