controller:
  resources:
    requests:
      cpu: 1
      memory: 1024Mi
    limits:
      cpu: 1
      memory: 1024Mi
worker:
  resources:
    requests:
      cpu: 5
      memory: 12288Mi
    limits:
      cpu: 5
      memory: 12288Mi